format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$direnv\
$cmd_duration\
$sudo\
$line_break\
$battery\
$character"""

[character]
format = '$symbol '
success_symbol = '[λ](bold green)'
error_symbol = '[x](bold red)'
vicmd_symbol = '[❮](bold green)'
disabled = false

[sudo]
disabled = false
