format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$direnv\
$cmd_duration\
$sudo\
$nix_shell\
$python\
$line_break\
$battery\
$character
"""

[character]
format = '$symbol '
success_symbol = '[λ](bold green)'
error_symbol = '[x](bold red)'
vicmd_symbol = '[❮](bold green)'
disabled = false

[sudo]
disabled = false

[nix_shell]
disabled = false
symbol = '❄️ '
format = 'via [$symbol(\($name\))](bold blue) '

[python]
disabled = false
version_format = 'v$major.$minor'
format = 'via [$symbol$version (\($virtualenv\))]($style)'

