theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = false
cursorline = true

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"C-d" = ["half_page_down", "goto_window_center"] 
"C-u" = ["half_page_up", "goto_window_center"]
